// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `calculate_folder_hash`, `collect_video_files`, `ensure_existing_directory`, `is_video_file`, `make_scan_entry`, `path_to_dart_string`, `sha256_hex`


            bool  isRustFileScanAvailable() => RustLib.instance.api.crateApiFileScanIsRustFileScanAvailable();

Future<RustFileScanSnapshot>  scanVideoFiles({required String folderPath }) => RustLib.instance.api.crateApiFileScanScanVideoFiles(folderPath: folderPath);

Future<RustFileScanDiff>  diffVideoFiles({required String folderPath , required List<RustFileHashEntry> cachedHashes }) => RustLib.instance.api.crateApiFileScanDiffVideoFiles(folderPath: folderPath, cachedHashes: cachedHashes);

            class RustFileHashEntry  {
                final String relativePath;
final String hash;

                const RustFileHashEntry({required this.relativePath ,required this.hash ,});

                
                

                
        @override
        int get hashCode => relativePath.hashCode^hash.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is RustFileHashEntry &&
                runtimeType == other.runtimeType
                && relativePath == other.relativePath&& hash == other.hash;
        
            }

class RustFileScanDiff  {
                final int currentCount;
final int cachedCount;
final List<String> currentFiles;
final List<String> newFiles;
final List<String> modifiedFiles;
final List<String> deletedFiles;
final String folderHash;
final List<RustFileHashEntry> currentHashes;

                const RustFileScanDiff({required this.currentCount ,required this.cachedCount ,required this.currentFiles ,required this.newFiles ,required this.modifiedFiles ,required this.deletedFiles ,required this.folderHash ,required this.currentHashes ,});

                
                

                
        @override
        int get hashCode => currentCount.hashCode^cachedCount.hashCode^currentFiles.hashCode^newFiles.hashCode^modifiedFiles.hashCode^deletedFiles.hashCode^folderHash.hashCode^currentHashes.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is RustFileScanDiff &&
                runtimeType == other.runtimeType
                && currentCount == other.currentCount&& cachedCount == other.cachedCount&& currentFiles == other.currentFiles&& newFiles == other.newFiles&& modifiedFiles == other.modifiedFiles&& deletedFiles == other.deletedFiles&& folderHash == other.folderHash&& currentHashes == other.currentHashes;
        
            }

class RustFileScanEntry  {
                final String relativePath;
final String absolutePath;
final PlatformInt64 size;
final PlatformInt64 modifiedMillis;
final String fileHash;

                const RustFileScanEntry({required this.relativePath ,required this.absolutePath ,required this.size ,required this.modifiedMillis ,required this.fileHash ,});

                
                

                
        @override
        int get hashCode => relativePath.hashCode^absolutePath.hashCode^size.hashCode^modifiedMillis.hashCode^fileHash.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is RustFileScanEntry &&
                runtimeType == other.runtimeType
                && relativePath == other.relativePath&& absolutePath == other.absolutePath&& size == other.size&& modifiedMillis == other.modifiedMillis&& fileHash == other.fileHash;
        
            }

class RustFileScanSnapshot  {
                final String folderHash;
final List<RustFileScanEntry> files;

                const RustFileScanSnapshot({required this.folderHash ,required this.files ,});

                
                

                
        @override
        int get hashCode => folderHash.hashCode^files.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is RustFileScanSnapshot &&
                runtimeType == other.runtimeType
                && folderHash == other.folderHash&& files == other.files;
        
            }
            